### ISSUE TITLE
error while reading from input stream with any Buffer

### ISSUE THREAD

**Issue by dragonfire535** [Automattic/node-canvas#1175]
## Issue or Feature

Any time I try to use a Buffer as the input for `loadImage`, I get the error `error while reading from input stream`. This happens consistently, I've tested both JPG and PNG buffers and both give the same error. The full stack is below, from when I was testing on my Discord bot's eval command:
```js
Error: error while reading from input stream
    at Image.src (/root/xiao/node_modules/canvas/lib/image.js:30:17)
    at Promise (/root/xiao/node_modules/canvas/index.js:34:15)
    at new Promise (<anonymous>)
    at loadImage (/root/xiao/node_modules/canvas/index.js:23:10)
    at snekfetch.get.then.res (eval at run (/root/xiao/node_modules/discord.js-commando/src/commands/util/eval.js:57:22), <anonymous>:1:149)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

## Steps to Reproduce

```js
const { loadImage } = require('canvas');

// with fs
const { promises: fs } = require('fs');
const image = await fs.readFile('some file');
const img = await loadImage(image); // error while reading from input stream

// with url
const snekfetch = require('snekfetch');
const { body } = await snekfetch('some url');
const image = await loadImage(body); // error while reading from input stream
```

## Your Environment
* Version of node-canvas (e.g. 1.4.0): latest master
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): Ubuntu 16.04.4

**Comment by dragonfire535** [comment]
https://i.imgur.com/2OmeiAr.jpg
Every single image I've tried does it, but here's one.

**Comment by user-9826342** [comment]
> Maybe you're not on latest master.

I've just fetched the node-canvas sources and I've built it from the master.
I downloaded your jpg file from the provided link and loaded it properly using the code you provided.

I tested on Windows 10, but I can't test on Ubuntu atm. Are you using the latest version of Node.js (v10.4.0)? Again, are you sure your images are not corrupted? Notice that if you upload an image to the imgur website, they re-encode it, so even if it was corrupted, the link you posted would provide a valid image.

**Comment by dragonfire535** [comment]
I am on latest node.js, my image is _not_ corrupted, all images don't seem to be working.

I managed to get images that are on my drive itself to load by simply supplying a path to the image, but that's not what this issue is, this issue is _only_ related to images supplied to `loadImage` as a Buffer, and those I supplied, be they read from fs or fetched from a website, refuse to load.

**Comment by user-9826342** [comment]
Does this work for you?

```js
var img = await loadImage(Buffer.from(
  '89504E470D0A1A0A0000000D4948445200000001000000010802000000907753' +
  'DE000000017352474200AECE1CE90000000467414D410000B18F0BFC61050000' +
  '00097048597300000EC300000EC301C76FA8640000000C49444154185763F8CF' +
  'C0000003010100632455D30000000049454E44AE426082'
, 'hex'));
```

If it works, then there is probably some issue with loading data buffer from the file system. If it doesn't work, then it is probably an issue with cairo on Ubuntu.

**Comment by dragonfire535** [comment]
That works, though I'm not sure why a simple Buffer like that would work but another wouldn't.

**Comment by dragonfire535** [comment]
Apologies, this seems to be a snekfetch issue.

**Comment by zbjornson** [comment]
@dragonfire535 if you know anything specific about why it was failing, it could be helpful if you post it here. This "error while reading from input stream" message gets reported a lot, so maybe we can improve the error message at least.

**Comment by user-9826342** [comment]
I think there are still few things that doesn't make sense.

@dragonfire535 You said that *"this seems to be a snekfetch issue"*. The `require('snekfetch')` is not a function itself, but `require('snekfetch').get` is a function (which also can be seen from your stack trace - ` at snekfetch.get.then.res`). Code `await snekfetch('some url')` throws TypeError telling you that `snekfetch` is not a function. Is what you posted a pseudo-code? Have you tested it in that exact form?

Also, it really doesn't make sense why `await fs.readFile('some file')` doesn't work for you. Are you actually tested with `fs`, or did you just test only using `snekfetch` and then concluded by intuition that it probably doesn't work with `fs` too? And is the `fs` module you're using the native Node.js module? If it doesn't work with `fs.readFile` (if the buffer is not loaded properly) then it may be an issue with `fs` module itself and should be filed on Node.js repo (in case it is reproducible).

@zbjornson *"maybe we can improve the error message at least."* - The method `get` of the `snekfetch` module fetches data in `utf8` encoding, which results in corrupted header of png or jpg files. I don't think there is anything that can be improven in the regard of error messages, since the header is invalid and node-canvas is unable to determine the format (png, jpg) of the given image buffer.

**Comment by dragonfire535** [comment]
@user-9826342 It should be `snekfetch.get`, sorry.

I did test with `fs.readFile` and it does indeed cause the error as well, I quickly assumed it was probably again not canvas' fault in this situation and rather fs itself (or in this case, the `fs.promises` API).

**Comment by user-9826342** [comment]
> I did test with fs.readFile and it does indeed cause the error as well

Then you should open an issue at [nodejs/node](https://github.com/nodejs/node/issues), since if `fs.readFile` returns a wrong buffer, then it is a Node.js issue which has to be fixed. I can't reproduce it though.
