### ISSUE TITLE
Not working on AWS Lambda

### ISSUE THREAD

**Issue by yellowmamba** [Automattic/node-canvas#1231]
## Issue or Feature
I installed prebuilt 2.0 to work with my lambda function. It works locally but when I deploy it to Lambda, it throws the following error from cloudwatch:

```module initialization error: Error at Error (native) at Object.Module._extensions..node (module.js:597:18) at Module.load (module.js:487:32) at tryModuleLoad (module.js:446:12) at Function.Module._load (module.js:438:3) at Module.require (module.js:497:17) at require (internal/module.js:20:19) at Object.<anonymous> (/var/task/node_modules/canvas/lib/bindings.js:3:18```

If I understand it correctly from this page. https://github.com/Automattic/node-canvas/wiki/Installation%3A-AWS-Lambda. 2.0 should work out of box, but apparently it doesn't. The example given in this doc indicates the code works with nodejs6.10, so I also tried to run it on nodejs6.10 on Lambda, didn't work. (I initially tried it on nodejs8.10, didn't work either)

## Steps to Reproduce

`handler.js`
```js
const { createCanvas } = require('canvas')
const canvas = createCanvas(200, 200)
const ctx = canvas.getContext('2d')

module.exports.index = function (event, context, callback) {
  console.log(event)
  ctx.font = '30px Impact'
  ctx.fillText('Awesome!', 50, 100)

  callback(null, '<img src="' + canvas.toDataURL() + '" />');
}
```

`serverless.yml`
```
service: my-service

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-southeast-2

functions:
  index:
    handler: handler.index
```

`package.json`
```
{
  "dependencies": {
    "canvas": "2.0"
  }
}
```

`sls invoke` works, but testing directly on Lambda doesn't.

## Your Environment
* Version of node-canvas (e.g. 1.4.0): canvas@2.0
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): aws nodejs6.10

**Comment by LinusU** [comment]
How are you packaging your app and sending it to Lambda? Maybe you are sending the macOS binary to the Lambda?

**Comment by jakelazaroff** [comment]
I'm also experiencing this issue. I'm packaging my app with Webpack and deploying it with Apex. Using Node 8.10 and I've tried with both 1.x and 2.x versions of node-canvas.

I made an example project to isolate node-canvas. It works locally but not when invoked from the AWS web console. Here's a gist of the project: https://gist.github.com/jakelazaroff/29e3e6d81c6cba1c6a8a10c09324c888

**Comment by zbjornson** [comment]
@jakelazaroff there's some info here: https://github.com/apex/apex/issues/468. Sounds like you need to deploy from an AWS Linux AMI for any native addons to work.

If we switch to the approach of bundling the binaries for all platforms in the tarball, I think that lends itself to a runtime selection of the right binary.

---

Re-reading the Lambda documentation ... I didn't realize Lambda itself requires the ZIP with all dependencies, it's not a convenience option that Apex and Serverless are taking advantage of. GCF avoids this issue with native deps by running `npm install` on their servers for you.

**Comment by LinusU** [comment]
> If we switch to the approach of bundling the binaries for all platforms in the tarball, I think that lends itself to a runtime selection of the right binary.

Yeah, this is probably a good approach 👍 

@yellowmamba if you want a quick fix you can look at building the zip-file that you send to Lambda inside of Docker. That's what I'm doing in the [`scandium`](https://github.com/LinusU/scandium) which I think is quite similar to apex.

The relevant code is here: https://github.com/LinusU/scandium/blob/master/lib/dockerfile.js

**Comment by jakelazaroff** [comment]
I tried installing the library inside of Docker (thanks for the reference code @LinusU), and it works perfectly! Here's [a gist with the working code](https://gist.github.com/jakelazaroff/29e3e6d81c6cba1c6a8a10c09324c888). You can just run `yarn prebuild` to build the Docker image, `yarn build` to actually compile it, and then just zip up all the files and upload them to AWS.

I was going to suggest adding that as a caveat to [this wiki page](https://github.com/Automattic/node-canvas/wiki/Installation:-AWS-Lambda), but it looks like y'all already added a link to this issue 😃 This can probably be closed now!

**Comment by tieTYT** [comment]
I want to make sure I understand the information in this issue correctly.  AWS Lambda is linux, I develop on a mac/windows.  If I install canvas on my computer, it uses the mac/windows binaries.  If I deploy the code to lambda, it'll get the mac/windows binaries which it can't use.

The solution could be for the binaries to include all OSes, including linux.  If it did, then what works on my mac/windows would work on Lambda.  But that hasn't been done yet, so in the mean time, I can work around this limitation by using Docker with a linux container to install the library, then copy that binary out of docker into my repo, then deploy the lambda with that docker-built library.  Do I have that right?

Theoretically, anyone could do this docker step once and share the binary on this issue so that nobody has to go through the docker step again, right?  The downside would be the binary may become out of date.

**Comment by zbjornson** [comment]
@tieTYT that's correct on the cause and a possible solution. I've not tried it but you should be able to skip the docker hassle and just download the correct binary from the prebuilt releases page (https://github.com/node-gfx/node-canvas-prebuilt/releases) if you're otherwise planning to manually copy from a Linux docker instance to your local machine. (Or, just publish to lambda from your docker container.)
