### ISSUE TITLE
Why is RGB24 data still 32 bits per pixel?

### ISSUE THREAD

**Issue by Noir-** [Automattic/node-canvas#1332]
My understanding of the RGB24 data format is that red, blue and green is encoded as 8 bits per color. I would assume that each 8 bit value is stored as an 8 bit integer so that the size of the buffer would be `width * height * 3`.

But it seems that the actual size of the buffer created by this library is `width * height * 4`.

[The current test cases](https://github.com/Automattic/node-canvas/blob/master/test/canvas.test.js#L866) are indicating that this is the correct behavior. 

I could imagine that the 8 bit values are packed into two 16 bit integer and one half of one integer is empty or something like that.

But I don't understand why it is done like that. For my application I need the 8 bit integer encoding.

**Comment by zbjornson** [comment]
That's indeed the intended behavior. Our reason for doing that is because that's what Cairo's underlying format uses. I'm not sure what Cairo's reasoning was, but it is fairly common to waste those 8 bits (e.g. Skia's `kRGB_888x_SkColorType`). It might be because it's easier to perform SIMD operations on 32-bit units; can be faster to address; and is very easy to convert to/from RGBA32 (all guesses though).

If you want to pack ImageData pixels in-place, you could use something like this:

```js
let i = 0, j = 0;
while (j < inp.length) {
	inp[i++] = inp[j++];
	inp[i++] = inp[j++];
	inp[i++] = inp[j++];
	j++;
}
// values i..end are unused
```
