### ISSUE TITLE
canvas.node is not a valid Win32 application.

### ISSUE THREAD

**Issue by FluffierThanThou** [Automattic/node-canvas#1370]
## Issue or Feature

`npm install canvas` and `npm install canvas --build-from-source` both complete successfully, but actually using canvas results in the above mentioned "canvas.node is not a valid Win32 application." error.

I'm fairly certain I've missed something obvious, but I'm out of ideas. Any help would be appreciated.

## Steps to Reproduce
???

## Your Environment
* canvas@2.3.1
* node v10.15.1 on Win 10 (node v8.11.1 also fails)

**Comment by zbjornson** [comment]
That error will happen if you've compiled for 64-bit Node.js and loaded it from 32-bit Node.js, or vice versa. (There might be other causes, but that's the common one.)

Do you need to build from source, or can you use prebuilds? (There are no 32-bit Windows prebuilds, so maybe that's why you're building.)

**Comment by FluffierThanThou** [comment]
I started by using the pre-built and tried both 64 and 32-bit versions of node v8. When that failed I installed node v10.15.1 as the latest LTS, hoping that might fix anything. I then tried building because I figured it might help, which also failed. If it matters, I use nvm (for windows) to manage node and npm versions.

There's no specific reason why I'd need to use 32-bit versions, or would have to build my own - I was just getting desperate for ideas.

**Comment by zbjornson** [comment]
I'm guessing node-gyp (building from source) and node-pre-gyp (prebuilt) are finding a 32-bit (or 64-bit) version of node installed by nvm, and you're running with 64-bit (or 32-bit) Node.js.

Can you post the output from `npm install canvas`/`yarn add canvas` please? It will say what platform node-pre-gyp detected when downloading the binary.

Then, when you get the "not a valid Win32 application", can you post the value of `process.arch`?

I'd try to eradicate any 32-bit Node.js binaries if you don't have a reason to use them. There are no prebuilds for that arch, it's an older arch and they're likely the cause of this issue. Doing a 32-bit build yourself also won't work due to #704, unless you build also cairo/pango/etc.

**Comment by sanjbuzzy** [comment]
We are struggling to fix this error while building and running a Meteor container using windows images - ltsc2019 or nanoserver:1809. The image runs 64bit versions of Node and confirmed running scripts and commands as in https://github.com/Automattic/node-canvas/issues/1597. Meteor version 1.10.2 and Node version 12.18.4 are used.

When the image is starting or running the app in the image (for debugging) following error is thrown. 
Error: \\?\C:\app\programs\server\npm\node_modules\canvas\build\Release\canvas.node is not a valid Win32 application.
\\?\C:\app\programs\server\npm\node_modules\canvas\build\Release\canvas.node.

We manually installed canvas (2.6.1) in the running container after remove the module comes from the build but still the same issue.

Appreciate if any direction to fix the issue.

**Comment by adamgins** [comment]
test 0: install buzzy Docker (2019 **nano**) - fails with node-canvas
test 1: install meteor on windows sever (2019 **base** - with full GUI) - this works
test 2: install zip file on windows server  (2019 **base** - with full GUI)  - ???
test 3: Docker image based off **servercore:ltsc2019**  mcr.microsoft.com/windows/servercore:ltsc2019 - fails with nodegyp
