### ISSUE TITLE
fillText fails if maxWidth set undefined

### ISSUE THREAD

**Issue by nomadoda** [Automattic/node-canvas#1454]
When I explicitly set the `maxWidth` option to `undefined` in `fillText`, the text doesn't render.

## Steps to Reproduce

```typescript
import { createCanvas } from 'canvas';
const canvas = createCanvas(200, 200);
const ctx = canvas.getContext('2d');
ctx.fillText('You can read this!', 50, 50);
ctx.fillText('You cannot read this!', 50, 50, undefined);
```

## Your Environment
* Version of node-canvas: 2.5.0
* Environment: Node v11.13, MacOS 10.14

**Comment by Hakerh400** [comment]
The fix is simple: in method `paintText` from `CanvasRenderingContext2d.cc` before calling `checkArgs`, if `argsNum == 3` and `info[3]->IsUndefined()` then decrement `argsNum`

However, the real question is whether this is a bug or not. In the specification it says that some methods have different behavior depending on the number of arguments provided (like `drawImage`, `fillText`, `strokeText`, etc). If any of the provided arguments up to the maximal number of arguments that the method takes evaluates to `NaN` when convertd to a number, the method has no effect. Thus, `fillText` takes 3 or 4 arguments, in case of 4 if you provide `undefined`, the method converts it to number, yielding `NaN` and nothing is drawn.

Not sure why Chrome and Firefox both draw text in that case. I filed an issue on the chromium bug tracker, still waiting for their response.

**Comment by nomadoda** [comment]
Interesting, I think that is a bit confusing. I was implementing a wrapper and it was hard to debug. Perhaps display some warning?

**Comment by LinusU** [comment]
> I filed an issue on the chromium bug tracker, still waiting for their response.

Great! Do you mind linking it? ☺️

**Comment by Hakerh400** [comment]
Here it is: [chromium#981645](https://bugs.chromium.org/p/chromium/issues/detail?id=981645)
