### ISSUE TITLE
node-pre-gyp (download 404) canvas-v2.6.0-node-v79-win32-unknown-x64.tar.gz

### ISSUE THREAD

**Issue by cavasinf** [Automattic/node-canvas#1500]
Hi,
I've a problem with NODEJS and canvas.

When installing the dependencies (npm install),
`node-pre-gyp` try to download your Pre-built binaries, but failed due to a file that not exist (404).

I don't know how your `guessing file name` work, but I think it's based on the environment and in my case it is wrong.
The file name which his trying to download is `canvas-v2.6.0-node-v79-win32-unknown-x64.tar.gz` .
How can I change the `v79` to `v64` ?

## Issue or Feature

```shell
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.0/canvas-v2.6.0-node-v79-win32-unknown-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.0 and node@13.3.0 (node-v79 ABI, unknown) (falling back to source compile with node-gyp)
```

## Steps to Reproduce

1. Init an express project
In My case I'm using express-generator https://www.npmjs.com/package/express-generator, and execute the command `express --view=twig`
2.
```shell
npm install canvas
```
3. Error

## Your Environment
* Version of node-canvas: canvas@2.6.0
* Environment: nodeJS 13.3.0 on Windows 10

**Comment by zbjornson** [comment]
> How can I change the v79 to v64 ?

v79 is the `NODE_MODULE_VERSION` for the version of Node.js that you're currently using (listed in [this table](https://nodejs.org/en/download/releases/)), so you generally shouldn't use something else because it won't be compatible. If you definitely want a different version for some reason, I think you can specify `npm i canvas --target=10.17.0`, which is NODE_MODULE_VERSION 64.

As far as why you're getting the 404, that's because Windows builds for Node.js v13 aren't available yet (listed at https://github.com/node-gfx/node-canvas-prebuilt/releases).

**Comment by cavasinf** [comment]
@zbjornson Fast answer, good solution with nice informations. Bravo Sir !
You made my day !

**Comment by bheema101** [comment]
please check your JAVA_HOME path it should be pointing to the C:\Program Files (x86)\Java\jdk1.8.0_121. you can override  to C:\Program Files\Java\jdk1.8.0_144
