### ISSUE TITLE
Question: font weight and style order

### ISSUE THREAD

**Issue by asturur** [Automattic/node-canvas#1620]
## Issue or Feature

In fabricJS code there is this comment since many years:

```js
ctx.font =  [
        // node-canvas needs "weight style", while browsers need "style weight"
        (fabric.isLikelyNode ? style.fontWeight : style.fontStyle),
        (fabric.isLikelyNode ? style.fontStyle : style.fontWeight),
        forMeasuring ? this.CACHE_FONT_SIZE + 'px' : style.fontSize + 'px',
        fontFamily
      ].join(' ');
```

Is this actally true? does ctx.font in node-canvas require weight and style in a different order?
And can we fix it with a getter or something in case?

**Comment by zbjornson** [comment]
We should be to-spec since #891 and #944 (2.0.0-alpha.1). See https://github.com/Automattic/node-canvas/pull/944/files for the tests and syntax:

```
[ [ <‘font-style’> || <font-variant-css21> || <‘font-weight’> || <‘font-stretch’> ]?
    <‘font-size’> [ / <‘line-height’> ]? <‘font-family’> ]
```

Before that it was reversed as you said: https://github.com/Automattic/node-canvas/commit/3d545056e2bb61b25f2d8bb1445c2e424a615163#diff-71d7843dbc8530a1e457267398396291L50-L55

**Comment by asturur** [comment]
ok so i should remove that code from fabric, is doing just mess.

Thanks.
