### ISSUE TITLE
"(process:15840): Pango-WARNING **: 20:41:16.548: couldn't load font "sans serif Not-Rotated 10px", falling back to "Sans Not-Rotated 10px", expect ugly output."

### ISSUE THREAD

**Issue by Pomax** [Automattic/node-canvas#1643]
Is there a way to prevent the warning `(process:15840): Pango-WARNING **: 20:41:16.548: couldn't load font "sans serif Not-Rotated 10px", falling back to "Sans Not-Rotated 10px", expect ugly output.`? My code doesn't issue a font instruction anywhere, so seeing it complain about not being able to fulfill "sans serif Not-Rotated 10px" is very odd indeed. I even tried setting an explicit `ctx.font = "sans not-rotated 10px";` but the warning still shows up.

**Comment by chearon** [comment]
The bit about not having any font instructions is surprising. That error gets triggered when Pango creates a cascade list for a section of text, which happens when you're rendering text, which happens due to `fillText` or `strokeText`. So I can't explain that, but the error itself seems to be happening for some people on Windows (eg #1608). Not sure why yet.

**Comment by Pomax** [comment]
ah yes, forgot that information: this is indeed Win10 pro x64, could it be that Pango is using the wrong naming format under water? (since "sans serif" is not a font, it's an entire category and not being able to find a single font in that category is basically impossible on any OS =)

**Comment by chearon** [comment]
Could be, here's where Pango defines those categories: 

https://github.com/GNOME/pango/blob/4ead5d2a2346c77a3dbc5e8d75221fa28e88f4e5/pango/pangowin32-fontmap.c#L464-L472

I don't know if `sans-serif` matches `sans serif` anywhere in the matching code, but if it doesn't, that would explain it. Do you see the error just by doing `require('canvas')` or does some drawing code trigger it?

**Comment by Pomax** [comment]
This yields no errors:

```js
import CanvasBuilder from 'canvas';
const canvas = CanvasBuilder.createCanvas(100,100);
const ctx = canvas.getContext('2d');
ctx.beginPath();
ctx.moveTo(0,0);
ctx.lineTo(100,0);
ctx.lineTo(100,100);
ctx.strokeStyle=`red`;
ctx.fillStyle=`green`;
ctx.stroke();
```

This does:

```
import CanvasBuilder from 'canvas';
const canvas = CanvasBuilder.createCanvas(100,100);
const ctx = canvas.getContext('2d');
ctx.fillText("and some text", 50, 50);
```

**Comment by chearon** [comment]
You probably only see the error once because Pango caches font sets aggressively. I don't know how I'm just now realizing this, but CSS uses `sans-serif` and Pango uses `sans`.

```
> require('canvas').createCanvas(100, 100).getContext('2d').font
'10px sans-serif'
```

We just have to do the translation from "sans-serif" to "sans" internally. Only problem is I don't know if macOS understands `sans-serif` which would change results for users. And it's not unlikely someone has a FontConfig configuration that knows what `sans-serif` is. So it could be a breaking change, OTOH people should probably be setting `font` if they want it to be consistent...

I'll open that PR now

**Comment by Pomax** [comment]
Nothing like a major semver update because "we fixed something, but it might have broken some people's configs, and we won't know until the bugs come rolling in" =P

**Comment by Pomax** [comment]
that is not the button I wanted to press >_>

**Comment by KingCodeSquid** [comment]
Windows problem, you must install the font first on your pc or it will give that error

**Comment by Pomax** [comment]
@KingCodeSquid how about reading an issue and the PR that fixed it before commenting on a solved, closed issue, first =)

**Comment by kevinforrestconnors** [comment]
> @KingCodeSquid how about reading the text of, and looking at the PR for, an issue, before commenting on something that's been resolved and closed for half a year, first =)

Except it's still broken on Windows =)

**Comment by kevinforrestconnors** [comment]
> > @KingCodeSquid how about reading the text of, and looking at the PR for, an issue, before commenting on something that's been resolved and closed for half a year, first =)
> 
> Except it's still broken on Windows =) @KCSquid 's comment helped me.
