### ISSUE TITLE
Font does not appear as bold (SuecaSlab)

### ISSUE THREAD

**Issue by TomFevrier** [Automattic/node-canvas#1747]
Hello there!

I have an issue with the SuecaSlab font. No matter which file I register in `registerFont()` (regular, semibold, bold, even heavy), it always appears with a normal weight. I tried converting the font file to TTF instead of OTF, but still the same issue. No problem with other fonts though.

Is there anything I'm doing wrong? Anyone with the same issue with other fonts?

## Steps to Reproduce
```js
const { createCanvas, registerFont } = require('canvas');
const { writeFileSync } = require('fs');

const canvas = createCanvas(1000, 600);
const ctx = canvas.getContext('2d');
registerFont('fonts/SuecaSlab-Bold.otf', {
	family: 'SuecaSlab'
});

ctx.font = "36px SuecaSlab";
ctx.fillText("This text should be bold but isn't", 40, 40);

writeFileSync('image.png', canvas.toDataURL().split(';base64,')[1], { encoding: 'base64' });
```

The font files are available here: [SuecaSlab.zip](https://github.com/Automattic/node-canvas/files/6031020/SuecaSlab.zip)

## Your Environment
* Version of node-canvas: 2.6.1
* Environment: node 14.15.1 on Mac OS X 10.15.7

**Comment by chearon** [comment]
Easy fix: call `registerFont` before `createCanvas`.

Why it needs to be in that order is mysterious. Neither Windows nor Linux have that problem. It should be available to the entire process until the program quits, yet macOS isn't returning the font in Pango's cascade list unless the canvas is created after.

Maybe I can find a real fix, but in the meantime, I need to go comment on a lot of issues. There's at least a few open that are caused by this.

**Comment by TomFevrier** [comment]
> Maybe I can find a real fix, but in the meantime, I need to go comment on a lot of issues. There's at least a few open that are caused by this.

I tried calling `registerFont()` before `createCanvas()` and it doesn't work neither. I ended up drawing the text twice with a 1px offset to make it appear bold... dirty but it looks alright.

**Comment by chearon** [comment]
Does the typeface look right, or does it look like Helvetica? The amount of boldness is determined by which font file you register. When I swap the `registerFont` and `createCanvas` calls, it works for me.

**Comment by TomFevrier** [comment]
It always looked right, no matter the order of the calls. Just the regular typeface, not the bold one.
Even weirder: when I didn't load the font at all it still appeared as the correct font with normal weight...

**Comment by chearon** [comment]
I see now. Do you have the fonts installed on your system? If I install the fonts, then I can reproduce the problem.

The font files you linked to are problematic because only the regular weight file has its `usWeightClass` set correctly. So node-canvas can't come up with distinguishing descriptors for each file.

**Comment by TomFevrier** [comment]
I see... I knew it must have been the font file because the other one I'm using (Calibre) was working fine.
