### ISSUE TITLE
error canvas.node

### ISSUE THREAD

**Issue by pumpkin39849** [Automattic/node-canvas#2039]
## Issue or Feature

node:internal/modules/cjs/loader:1189
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified procedure could not be found.
\\?\C:\Users\node_modules\canvas\build\Release\canvas.node
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
}

## Steps to Reproduce
```js
const Canvas = require('canvas');
```

## My Environment
* Version of canvas: 2.9.1
* Version of npm: 8.9.0
* Version of node: 16.15.0

i reinstalled nodejs deleted node_modules package.lock.json and node persist and install everything back with "npm i", also tried 
npm i canvas
npm rebuild canvas

and

npm rebuild bcrypt

and

npm rebuild bcrypt --build-from-source
 nothing fix the issue till now

**Comment by 0x6c23** [comment]
Same issue.

```
Error: The specified procedure could not be found.
\\?\E:\..\..\node_modules\canvas\build\Release\canvas.node
```

I also tried building from source, building worked but the error persists.

**Comment by zbjornson** [comment]
There are a few possible reasons for this listed in https://github.com/Automattic/node-canvas/issues/1219#issuecomment-411288069. Unfortunately the error message is too generic to provide more specific guidance. You might also find useful info if you open node_modules\canvas\build\Release\canvas.node with depends.exe (available free from https://www.dependencywalker.com/).

**Comment by MetaverseMan** [comment]
I use macOS  Monterey 12.4,I have been troubled in the same issue all day ,trying to find an solution here and there ,but nothing works and cause some new problems came out, and finally i decide to follow the readme tutorial "npm install --build-from-source"  and  it works.  I believe there are something wrong with npm when you trying to  use npm command to  download  the  released assets in this repository, according to the log in my terminal , the url was incorrect .then i download it manually , npm run build ,it Error like this:/node_modules/canvas/build/Release/canvas.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')),apparently this problem is about the architecture ,so i just decide to install dependencies and use   "--build-from-source" method . so happy it works.

**Comment by MetaverseMan** [comment]
I use macOS Monterey 12.4,I have been troubled in the same issue all day ,trying to find an solution here and there ,but nothing works and cause some new problems , and finally i decide to follow the readme tutorial "npm install --build-from-source" and it works. I believe there are something wrong with npm when you trying to use npm command to download the released assets in this repository, according to the log in my terminal , the url was incorrect .then i download it manually , npm run build ,it Error like this:/node_modules/canvas/build/Release/canvas.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')),apparently this problem is about the architecture ,so i just decide to install dependencies and use "--build-from-source" method . so happy it works.

**Comment by LEV7n** [comment]
I too when compiling it for electron usage

**Comment by Orangenal-name** [comment]
Why was this closed as completed? I am still having this issue, when I have not had it before.

**Comment by MrlolDev** [comment]
Pls post an actual fix soon

**Comment by yonaodesign** [comment]
Any updates?

**Comment by Shubhamrawat5** [comment]
same error
