### ISSUE TITLE
supporting Apple M1 ?

### ISSUE THREAD

**Issue by wgh815600709qq** [Automattic/node-canvas#2253]
I meet some error when I use Apple M1 Pro system to install the package, any idea to support Apple M1 Pro system?

![image](https://github.com/Automattic/node-canvas/assets/17962624/59643ac8-314f-4eef-a100-b7bac08e066b)

**Comment by trickeyone** [comment]
Running into this issue as well. Saw #2036 and tried the solutions listed there to no success.

**Comment by liambolling** [comment]
Running into this issue as well

**Comment by antonio-iodice** [comment]
Hey everybody. Same problem here. Is there a guideline on how to prepare a prebuild (@zbjornson maybe?)? Maybe someone, me included, could support with this?

**Comment by charlesoconor** [comment]
Could the library possibly publish one for an M1 Mac as well, so we don't have to build it from source?

**Comment by coderfin** [comment]
I'm not associated with this project or https://github.com/Brooooooklyn/canvas but I found that https://www.npmjs.com/package/@napi-rs/canvas is a great replacement for node-canvas. `@napi-rs/canvas` supports Intel and Arm (M Chip) Macs with no system dependencies.  It supports all the same features that I needed.  It also supports `webp` which was a welcome bonus and is MIT license.

Instead of `registerFont` use `GlobalFonts.registerFromPath`; `createCanvas` and `loadImage` remain the same.

**Comment by chearon** [comment]
Prebuilds are working for macOS/Arm since #2354 was merged!

`npm install canvas@next` to get 3.0.0-rc3. I'm going to wait a few days before releasing 3.0.
