### ISSUE TITLE
"ERR_DLOPEN_FAILED" error when using the pkg tool

### ISSUE THREAD

**Issue by bigboss2944** [Automattic/node-canvas#2316]
Issue Summary

Encountering the "ERR_DLOPEN_FAILED" error when using the pkg tool.

DescriptionContext: 
I am attempting to package my Node.js application including canvas package using the pkg tool to create an executable. However, I am running into the following error:Error: error: 126C: code: 'ERR_DLOPEN_FAILED' at process.dlopen (pkg/prelude/bootstrap.js:2251:28)

Steps to Reproduce:

-Reproduce the steps explained in the link here after to recreate the nodejs app
https://www.section.io/engineering-education/compile-your-nodejs-application-into-a-exe-file/

-Add the canvas package
-import the canvas package in your index file
-Run the following command: node index.js then pkg index.js and .\index-win.exe
-Observe the mentioned error.

Expected Behavior: 
I expected the pkg command to generate a working executable without encountering any "ERR_DLOPEN_FAILED" errors.

Actual Behavior: 

The pkg command fails with the mentioned error, making it difficult to generate a functional executable.

Environment

Node.js Version: Node.js v16.17.0, 18.5.0 and 18.17.0
Operating System: windows 10
pkg Version: pkg v5.8.1

Additional Context

This issue occurs consistently. The exe file generated without canvas works correctly.

Screenshots or Code Snippets
![image](https://github.com/Automattic/node-canvas/assets/51483078/10c3f25d-c46d-42ae-ba90-d7057888a2ab)

**Comment by mn4367** [comment]
Probably this is not a problem with `canvas` but with your usage of `pkg`. You have to tell `pkg` to add the contents of the folder `node_modules/canvas/build/Release/` in the generated executable. Please see the `pkg` [docs](https://github.com/vercel/pkg#assets).

**Comment by mn4367** [comment]
I think there is an error in the `assets` section. Every entry there must be a separate path, but you have only one entry in the array (could be a typo). So it's rather:

```
"assets": [
  "node_modules/**/*",
  "views/**/*" 
],
```

But using `"node_modules/**/*"` is also 'wrong' because that would pack *all* Node modules into the executable which is something that you don't want to have. During packaging your application `pkg` will analyze your code and determine what has to be contained in your executable. This is done by inspecting and following all `require` statements in your code. Usually this works very well, but in your case `pkg` has no chance to determine that the native `canvas` module (`node_modules/canvas/build/Release/canvas.node`) relies on some additional DLLs so you have to make sure manually that these DLLs are also packaged into the executable. This is why I said that you'd have to use `node_modules/canvas/build/Release/` since this is the directory which contains the additional DLLs. So using

```
"assets": [
  "node_modules/canvas/build/Release/**/*",
  "views/**/*" 
]
```

should work.

**Comment by mn4367** [comment]
That's correct. On the very first start of your executable `pkg` always unpacks native modules into a folder under `AppData` because these modules must be loaded from a real file system instead of a virtual file system. Please take a look inside this generated folder, it should contain the same files as `<your-project-dir>/node_modules/canvas/build/Release`. One last idea: did you install `canvas` locally or globally? I think for this use case you should uninstall completely any globally installed instance of `canvas` and reinstall it locally only in the project(s) that are using it. Please also note that `pkg` should be listed in `devDependencies` not in `dependencies`.

Although many Node modules recommend to use `npm i g <module>` I almost always really try hard to avoid that. Installing Node modules always local to your projects with `npm i <module>` comes at the cost of disk space but avoids all kinds of dependency nightmares with different required module versions in different projects.

It could also be helpful to completely remove the folder `AppData/Local/Temp/pkg` and see what it contains after starting your executable. 

I'm writing all this because I have the exact same use case here and it works on MacOS, Windows and Linux the way I described it.

**Comment by mn4367** [comment]
So I assume that you have these files in your `AppData/Local/Temp/pkg/7a51bbe...4ee7b1/canvas/build/Release` folder?

```
canvas.iobj
canvas.ipdb
canvas.lib
canvas.node
canvas.pdb
libbrotlicommon.dll
libbrotlidec.dll
libbz2-1.dll
libcairo-2.dll
libcairo-gobject-2.dll
libdatrie-1.dll
libexpat-1.dll
libffi-8.dll
libfontconfig-1.dll
libfreetype-6.dll
libfribidi-0.dll
libgcc_s_seh-1.dll
libgdk_pixbuf-2.0-0.dll
libgif-7.dll
libgio-2.0-0.dll
libglib-2.0-0.dll
libgmodule-2.0-0.dll
libgobject-2.0-0.dll
libgraphite2.dll
libharfbuzz-0.dll
libiconv-2.dll
libintl-8.dll
libjpeg-8.dll
liblzma-5.dll
libpango-1.0-0.dll
libpangocairo-1.0-0.dll
libpangoft2-1.0-0.dll
libpangowin32-1.0-0.dll
libpcre2-8-0.dll
libpixman-1-0.dll
libpng16-16.dll
librsvg-2-2.dll
libstdc++-6.dll
libthai-0.dll
libwinpthread-1.dll
libxml2-2.dll
zlib1.dll
canvas.exp
```

**Comment by fabrice-noel29** [comment]
I just have canvas.node and that's all

**Comment by fabrice-noel29** [comment]
package.json
{
  "name": "helloworld",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "bin": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "canvas": "^2.11.2",
    "express": "^4.18.2"
  },
  "pkg": {
    "scripts": "build/**/*.js",
    "assets": [
      "node_modules/canvas/build/Release/**/*",
      "views/**/*"
    ],
    "targets": [
      "node18-win-x64"
    ],
    "outputPath": "dist"
  },
  "devDependencies": {
    "pkg": "^5.8.1"
  }
}

**Comment by fabrice-noel29** [comment]
and to generate the exe : 
pkg .

**Comment by mn4367** [comment]
I'll come back to you soon.

**Comment by mn4367** [comment]
OK, here is a simplified version of what you gave to me:

package.json:
```
{
    "name": "hellocanvas",
    "version": "1.0.0",
    "main": "index.js",
    "bin": "index.js",
    "scripts": {
        "make-exe": "pkg -c pkg.json index.js"
    },
    "dependencies": {
        "canvas": "^2.11.2"
    },
    "devDependencies": {
        "pkg": "^5.8.1"
    }
}
```

pkg.json:
```
{
    "name": "hellocanvas",
    "version": "1.0.0",
    "description": "Canvas sample",
    "pkg": {
        "assets": [
            "node_modules/canvas/build/Release/**/*"
        ],
        "targets": [
            "node18-win-x64"
        ],
        "outputPath": "dist"
    }
}
```

index.js:
```
const canvas = require("canvas");
const fs = require("fs");

console.log("Hello canvas!")

const c = canvas.createCanvas(600, 600);
const ctx = c.getContext("2d");

ctx.fillStyle = "lightgrey";
ctx.fillRect(0, 0, 600, 600);

ctx.font = "40pt 'serif'";
ctx.fillStyle = "black";
ctx.fillText('Hello canvas!', 20, 100);

const JPEGData = c.toBuffer("image/jpeg", { quality: 0.75, progressive: true });
fs.writeFileSync("test.jpeg", JPEGData);

console.log("Image written to test.jpeg");
```

Please create an empty directory with the three files above and then delete everything under `AppData/Local/Temp/pkg`. 

Then run `npm i`. You should now be able to test the sample with `node index.js`. A successful test should create a JPEG file in the current folder. Afterwards run `npm run make-exe`. This should create an executable in `dist`. Calling `hellocanvas.exe` in the directory `dist` should create the same JPEG file in `dist`. Also the directory `AppData/Local/Temp/pkg/<temp_string>/canvas/build/Release` should now contain all the needed files (mostly DLLs) required by the native canvas module file `canvas.node`.

I've separated the configuration for `pkg` into its own file because that has the advantage of being able to create different targets (Node version, platform etc.) from a single `package.json`.

Does that work?

Explanation: `pkg` traverses all dependencies (calls to `require`) of your project and packs these files into the executable. For native modules like `canvas` that only works partially. Why? `pkg` can see that your code uses `canvas` and therefore `canvas.node` (by seeing something like `require("canvas.node")`) so it will pack `canvas.node` and the majority of files of that module into the executable as well. On the first execution it unpacks the module into a temporary folder (under `AppData/Local/Temp/...`) because native modules can only be loaded from a physical file system but not from the virtual file system inside your executable. But `pkg` is unable to detect that the native module file `canvas.node` itself tries to load further DLLs and so you have to tell `pkg` to include those files. That's done with `"assets": ["node_modules/canvas/build/Release/**/*"]`.

By the way, it's always safe to remove the directory `AppData/local/Temp/pkg` because the executable will check always if it finds its dependencies there. If they are missing, they will be recreated.

**Comment by mn4367** [comment]
I forgot to mention that I've tried my example with the three files from above on Windows and it worked. Not using `"assets": ["node_modules/canvas/build/Release/**/*"]` leads to the same problem you saw.

**Comment by bigboss2944** [comment]
Yes it worked (but only with node 18.5.0 min). Thanks a lot for your help and your explanations very precise. And you are right. I thought that my problem was due to canvas but it is due to pkg. So I will close the issue

**Comment by mn4367** [comment]
De rien :-).
