### ISSUE TITLE
Version 3.x with pdfjs error - Cannot assign to read only property

### ISSUE THREAD

**Issue by abrenoch** [Automattic/node-canvas#2446]
Hey, taking a crack at getting the v3 of this library to play nicely with pdf.js, running into this error:

```
TypeError: Cannot assign to read only property 'clip' of object '#<CanvasRenderingContext2D>'
```

I mentioned this same issue with the `save` property in the PR here:
https://github.com/Automattic/node-canvas/pull/2235#issuecomment-1759625588

Are there more read-only properties that need to be changed?

**Comment by rory-orennia** [comment]
I'm getting similar errors while trying to use Vega (https://github.com/vega/vega) on version 3.
`TypeError: Cannot assign to read only property 'width' of object '#<Canvas>'`. Then I patch the library to take out that line just to see if I can get it working and `TypeError: Cannot assign to read only property 'globalCompositeOperation' of object '#<CanvasRenderingContext2D>`.  Take that out and then `TypeError: Cannot assign to read only property 'globalAlpha' of object '#<CanvasRenderingContext2D>'`. keep going `TypeError: Cannot assign to read only property 'strokeStyle' of object '#<CanvasRenderingContext2D>`. and again `TypeError: Cannot assign to read only property 'lineWidth' of object '#<CanvasRenderingContext2D>'` and finally `TypeError: Cannot assign to read only property 'lineDashOffset' of object '#<CanvasRenderingContext2D>'`.

After all that you get a beautiful chart of nothing because you took away all the drawing pieces 🤣

**Comment by abrenoch** [comment]
Actually it looks like there have been changes made since RC2 was released that may address this issue.

@zbjornson Any chance we could get some new prebuilds up with these changes? Pretty please! 🙏

**Comment by rory-orennia** [comment]
There's a few stories in Bun and Deno around this so it would be great to see how close we are with the latest changes:
https://github.com/oven-sh/bun/issues/5835
https://github.com/denoland/deno/issues/26347
https://github.com/denoland/deno/issues/25974

The reason I was testing vega with node-canvas 3.0 was because I wanted to test the performance improvements of either bun or deno against our current node server, and version 2 is basically unusable in either of those newer runtimes

**Comment by Methuselah96** [comment]
I am also experiencing these errors when using with jsdom. @zbjornson Any chance we can get a new RC release with the fixes?

**Comment by prescottprue** [comment]
Also seeing this issue with pdfjs - would be awesome to see a new RC with the fixes as called out

**Comment by jacob-israel-turner** [comment]
The pdf.js team just [removed](https://github.com/mozilla/pdf.js/pull/19015) the `node-canvas` dependency, so this shouldn't be an issue in the next release.
