### ISSUE TITLE
Font Encoding or Secondary font

### ISSUE THREAD

**Issue by rcyrus** [Automattic/node-canvas#266]
Greetings. Thank you for making node-canvas as awesome as it is! 

I'm using node-canvas to rasterize content that I had previously created in a web browser. 
Almost everything works great, the only exception is non-standard text with custom fontFace. 

'normal' text works fine but when I try something extended I get a rectangle instead of the symbol.
Examples:
Text on my browser.
![browser](https://f.cloud.github.com/assets/276867/286506/63bc9ad6-923e-11e2-8e04-90f30b6c40a7.png)

Same text rendered from node-canvas.
![node-canvas](https://f.cloud.github.com/assets/276867/286514/7f7e5dfe-923e-11e2-928d-6990e41a5428.png)

The font in question is [Quattrocentro](https://www.google.com/webfonts/specimen/Quattrocento).

Quattrocentro does not have that symbol but I was hoping it would fallback to a secondary font to fill in like a browser would. 

Is there a way for node-canvas to do this or am I SOL when it comes to extended characters?

**Comment by ryuukibeat** [comment]
Sorry to bump the old issue, but I have this same issue when mostly render Japanese, arabic, and other Unicode fonts.

node-canvas version: v2.0.0-alpha.1

I use that version because I want custom fonts with `Canvas.registerFont(path_to_font, { family: 'MyFont' })`
But when the font doesn't have the glyphs (Japanese, etc), it just shows square and no fallback.

How do I achieve custom fonts (TTF) and fallback fonts using that version? Or is there a better solution?

**Comment by chearon** [comment]
Are you using Windows? Pango font substitution [doesn't work](https://bugzilla.gnome.org/show_bug.cgi?id=162681) there. But you can specify a comma separated list when you set `ctx.font` and it should use them in order.

**Comment by ryuukibeat** [comment]
My dev OS is windows. So I need to specify multiple fonts that support unicode? For example `ctx.font = "15px MyFont, Arial, Sans";`?

And my end product OS is Ubuntu LTS 16.04, still print square txt. The only attempt in ubuntu I take is only `sudo apt-get install fonts-arphic-uming fonts-ipafont-mincho ttf-wqy-zenhei ttf-unfonts-core fonts-takao fonts-dejavu ttf-mscorefonts-installer`.

**Comment by chearon** [comment]
Closed via #715
