### ISSUE TITLE
toBuffer optimization

### ISSUE THREAD

**Issue by kangax** [Automattic/node-canvas#306]
I ran into performance issues with `toBuffer`. Here's an example of drawing (rather) large image onto canvas, then calling `toBuffer`. `toBuffer` is what's taking the longest here (`drawImage`, for example, is insignificant). I'm getting ~7-7.5 sec on `toBuffer` call. This is on node v0.10.13, node-canvas v1.0.3, and Mac OS X (10.7.5).

Is there a way to speed things up? Anything at all? I also tried async `toBuffer` but it doesn't really help.

``` js
var fs = require('fs'),
    Canvas = require('canvas'),
    Image = Canvas.Image;

// 3.9MB, 4686x4668
fs.readFile(__dirname + '/big_img.jpg', function(err, bigImg) {
  if (err) throw err;

  img = new Image;
  img.src = bigImg;

  var canvas = new Canvas(img.width, img.height);
  var ctx = canvas.getContext('2d');

  ctx.drawImage(img, 0, 0);

  console.time('toBuffer');
  canvas.toBuffer();
  console.timeEnd('toBuffer'); // 7196ms, 7435ms, 7237ms
});
```

Attaching image used in a test.

![big_img](https://f.cloud.github.com/assets/383/862630/b4f4d900-f5f7-11e2-888e-2c2289c6edd0.jpg)

**Comment by benzmuircroft** [comment]
https://github.com/Automattic/node-canvas/issues/562 webp is 13% in size of a png and 87% space saved! If webp support is not provided by the uses choice in browser then they will have png fall back.

Webp is supported on Chrome so users of chrome should be advantaged with lower size images and a faster browsing experience.

**Comment by adamhooper** [comment]
Isn't the obvious solution to make this library _not_ encode image data?

In my dream world, `toBuffer()` returns a Buffer of native-endian ARGB32 pixel data: no encoding whatsoever. That would give users their choice of encoding libraries, at the cost of a single `memcpy()`.

Side-benefits: node-canvas would be easier to maintain and wouldn't depend on libpng or libjpeg.

Obviously, that's a breaking change. During transition, `toBuffer('argb32')` would be backward-compatible....

**Comment by zbjornson** [comment]
@adamhooper `getImageData` returns a `Uint8ClampedArray` of RGBA values, which sounds like what your asking for, except for the color depth?

**Comment by adamhooper** [comment]
@zbjornson Ooh, didn't see that method.

It's similar, but not the same: the _purpose_ is completely different. `getImageData()` is built to be compatible with HTML5; `getBuffer()` is built to encode. There should be a method whose _purpose_ is to access raw pixel data.

(Furthermore, I opine that the method to access raw pixel data should be called `toBuffer()`, and I opine that the current `toBuffer()` should be called `toPNGBuffer()`. This suggestion is surely more controversial/problematic.)

`getImageData()` does two things that are not appropriate in this method:

1. It rotates the values from RGBA to ARGB
2. It premultiplies alpha values. This is lossy, and because of the RGBA->ARGB conversion, the whole method is slower than `memcpy()`, even for fully-opaque images.

Obviously, `getImageData()` _must_ rotate and premultiply. Equally obviously, rotating and premultiplying are inappropriate for other image-encoding libraries.

I think there's room in the Node ecosystem to put pixel-manipulation and image-encoding in separate libraries. Maybe I'd like to do custom pixel-manipulation (like giving pixel `(0,0)` alpha `254`, so Twitter doesn't convert my PNG to JPEG). Maybe I'd like to convert to indexed RGB. Maybe I'd like to use LodePNG, node-png (with truly custom parameters), JPEG (fully customized), WebP (#562), etc.

(As it so happens, I want to do all those things :))

There's no substitute for `memcpy()` in a canvas library. `toBuffer()` is far too slow; `getImageData()` is lossy (and still a bit slow).
