### ISSUE TITLE
Using sx and sy with drawImage creates "empty" output

### ISSUE THREAD

**Issue by oemueller** [Automattic/node-canvas#341]
Hi, 
I'm trying to split up large PNG files into smaller tiles. 
Original files are 8192 x 2048, tiles will be 256. 

The first tile at sx 0, sy 0 gets exported correctly, but every other sx/sy position creates a black/empty output file.

ctx.drawImage(img, 0, 0, targetSize, targetSize, sx*targetSize, sy*targetSize, targetSize, targetSize );

sx and sy changes in every iteration.

Any idea what's wrong about drawImage in my case?

Thanks

**Comment by bennlich** [comment]
@oemueller I think you might have your parameters mixed up. See [here](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage). It should look something like:

`ctx.drawImage(img, srcX, srcY, srcWidth, srcHeight, dstX, dstY, dstWidth, dstHeight)`

But in your example it looks like you're changing `dstX` and `dstY` instead of `srcX` and `srcY`. Is that intended?
