### ISSUE TITLE
Certain base64 URL not loading on OSX

### ISSUE THREAD

**Issue by JJJollyjim** [Automattic/node-canvas#361]
I'm trying to load [this base64 image](http://pastebin.com/anhMzCRj) into a canvas. All other images work fine, but this single image never loads. It never calls the onload handler, and using it gives an image not loaded error, even several seconds later. However, if I do the exact same thing (the same code in a node.js repl) on my heroku server (with [this](https://github.com/mojodna/heroku-buildpack-cairo) buildpack), it loads fine. Browsers can display the image perfectly fine as well. This is a most unusual bug… any ideas?

**Comment by zbjornson** [comment]
(5 years later...)

That is a GIF, not a PNG, so it should begin with `data:image/gif;base64` instead of `data:image/png;base64`. (node-canvas doesn't use that prefix when decoding the image though, it looks for a magic number in the image data, like browsers do.) I'm guessing you had gif support on your heroku server but not your OSX machine.
