### ISSUE TITLE
Canvas Image src needs +=

### ISSUE THREAD

**Issue by maxstudener** [Automattic/node-canvas#413]
I'd like to download an image from external source and on req.on('data', function(chunk)) id like to take the stream chunks of image from external source to canvas then on req.on('end') id like to then ctx.drawImage

**Comment by LinusU** [comment]
What @TooTallNate said, allowing `src += _` would just move the buffer from you program to canvas, it wouldn't make a difference...

I don't actually think that there would be any added memory benefit of reading the file chunk by chunk, since that would require you to either allocate the entire raw image on the first chunk, or do excessive copying of data...

I'm closing this for now, if anyone has more information or thoughts on how this should be implemented, please feel free to reopen...
