### ISSUE TITLE
Why after saving a SVG file, later modifications on canvas can't be saved in another SVG file?

### ISSUE THREAD

**Issue by q2dg** [Automattic/node-canvas#484]
I mean...

var fs = require("fs")
var Canvas = require("canvas")
var canvas = new Canvas(200,200,"svg")
var ctx = canvas.getContext("2d") 
ctx.fillRect(0,0,100,100)    //Black square
ctx.save()
ctx.fillStyle = "darkblue" 
ctx.fillRect(0,0,100,100)   //Blue square
fs.writeFileSync("square1.svg", canvas.toBuffer())  **//Saves blue square. Ok**
ctx.restore()
ctx.fillRect(0,0,100,100)   //Black square again, in theory
fs.writeFileSync("square2.svg", canvas.toBuffer()) **//Should save black square,but saves blue square!**

BONUS: If I comment the line which creates square1.svg file, then square2.svg does show the black square!!

**Comment by zbjornson** [comment]
First one: Evidently it's only possible to call `canvas.toBuffer()` *once* if it's a PDF or SVG canvas because `cairo_surface_finish` is a finalizing call. Currently I get an assertion failure if I call `toBuffer` twice, but perhaps some cairo version silently ignored subsequent drawing calls. I'm not sure what the best fix for this is (maybe storing a copy of the surface in `toBuffer`, but that would be a bit expensive). I'll open a new issue for that.

Second and third: You need to call [`ctx.beginPath()`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/beginPath) between paths. Something like this:

```js
ctx.arc(50,50,30,0,2*Math.PI) ; ctx.stroke() //Circumference
ctx.beginPath()
ctx.arc(150,50,30,0,2*Math.PI) ; ctx.fill() //Filled circle
ctx.beginPath()
ctx.arc(50,150,30,Math.PI/4,3/2*Math.PI)
ctx.strokeStyle="red" ; ctx.stroke() ; ctx.fill() //Filled arc
```

![out](https://user-images.githubusercontent.com/469365/42147607-7a551a76-7d83-11e8-8ae6-9b78d6036321.png)
