### ISSUE TITLE
200 open issues? This project needs more maintainers.

### ISSUE THREAD

**Issue by ronkorving** [Automattic/node-canvas#500]
I'm calling upon @tj (should I bother? :)), @TooTallNate, @rvagg and @kangax to find more maintainers. Clearly this project is not being managed like it should, which is a real shame for such a useful library.

If anybody feels like they could contribute by maintaining this repo, I urge you to respond to this issue and volunteer. Then I can only hope the people mentioned above will give you the access you need to help out.

**Comment by tj** [comment]
Not sure if anyone who used to be involved still actively uses it, hopefully some new community members are interested!

**Comment by ronkorving** [comment]
Me too :) (ironic how the first responder is the one guy who pretty much renounced Node ;) it's appreciated)

**Comment by tj** [comment]
My GH notifications are no longer a huge mess :D

**Comment by kangax** [comment]
I called for help in the past — https://twitter.com/kangax/status/388032790618710017 — but there isn't much contribution. The best help would be if someone familiar with filesystems, compilations, and various dependencies (cairo, etc.) went over all installation-related issues and figured out the biggest sources of problems. I think at least half of the issues are installation-related. Other stuff is PR's that might have useful fixes or additions, but those need to be looked at by someone who knows the internals (I don't).

**Comment by rvagg** [comment]
The biggest problem here is the heavy reliance on C++ and the quirks of Node.js addon development. I've contributed in the past where I've had use for this lib and will probably contribute again in the future, but I just don't have time to deal with feature requests from people who don't have any code to contribute. I'd love for more Node devs to step out of their comfort zone a little and not be so afraid of lower-level coding, but that's a huge barrier for most.

I'm generally happy to be dragged into discussions around code in here though, so where there's review that needs to be done, please ping me, just don't expect me to implement something I have no direct use for (I suspect the same goes for other people involved here, therein lies OSS burnout).

**Comment by ronkorving** [comment]
That's kinda the situation I'm in. I don't actually use this project myself, but see others use it. It's hard to convince them to contribute when they look at the state of things. Sadly, the conversation moves to looking for alternatives. I hope node-canvas has a brighter future than that.

**Comment by rvagg** [comment]
I'm happily using it in production for nodei.co still so it's not completely out of my view.

**Comment by kangax** [comment]
> Sadly, the conversation moves to looking for alternatives.

But are there? :) I don't think so. That's the crazy/sad part.

FWIW, we're relying on node-canvas in Fabric.js and we use Fabric.js on production (~150K visits/mo) for few years and still. It works but it's buggy at times and we don't touch it while it's not terribly broken. 

Here's a list of Fabric limitations, all due to node-canvas — https://github.com/kangax/fabric.js/wiki/Fabric-limitations-in-node.js Sometimes I hear Fabric users run into these and there isn't much I can do (aside from perhaps hiring someone to look into it).

It's certainly sad to rely on a project that's not actively maintained but I don't see an alternative so far.

**Comment by ronkorving** [comment]
When I say "alternatives", that even includes reinventing the wheel. Something I desperately try to avoid :) Thanks for those links and backstory btw.

**Comment by tj** [comment]
There's not a huge demand for this sort of thing unfortunately. I think I remember seeing a phantomjs style solution that was webkit based, that might be worth looking into.

**Comment by kangax** [comment]
You're right, that's part of the problem. I think I've seen that webkit solution as well, even tweeted about it, but can't find it now. In any case, it wasn't that much of a competitor, AFAIR.

**Comment by ronkorving** [comment]
It seems for WebGL users, there's https://github.com/mikeseven/node-webgl as well.

**Comment by jakeg** [comment]
Glad to see this thread :)

We use node-canvas (specifically PDF output) along with a <canvas> web-based page designer that we built to create printed, hard-copy yearbooks here at http://allyearbooks.co.uk .

Unfortunately I'm the only developer here at present and have never used C++ before (my remit is more PHP and now increasingly JavaScript) so I'm not sure how much value I'd be to help maintain the code other than adding and replying to issues and making the odd pull request. We used to have someone here who added PDF output support to node-canvas but he's since left.

We're currently running on a slightly forked copy of node-canvas as we required this pull request:
https://github.com/Automattic/node-canvas/pull/490

I think one of the most annoying things in terms of lack of maintenance isn't the number of issues but the number of pull requests adding potentially useful features and bug fixes which seem to get ignored.

If it interests anyone, we (AllYearbooks) could potentially offer some financial support to the project, though I don't know how that could work exactly.
