### ISSUE TITLE
Pango nightmares

### ISSUE THREAD

**Issue by rvagg** [Automattic/node-canvas#570]
I just upgraded https://nodei.co and had to yak shave my way to find a solution to my custom fonts not showing up any more. I believe related to this problem are #548 and #561. The workaround was to revert pango being enabled as it was in 7522aca2ea7d4e38752cfef807b31ba1a419d58f at which point everything worked again.

Scanning some of the recent font related problems in the issues I wouldn't be surprised if this is biting a large number of people and perhaps we should view it as a breaking change and revert that commit (or at least pango being enabled).

**Comment by jakeg** [comment]
Personally I'd like to see making pango a requirement.

As you say, lots of issues/frustrations have come up recently in relation to font problems, and I think part of this is that some people are installing with pango, others without, and without pango some things (e.g. fallback fonts) just aren't possible.

Is there a good reason for not making pango a requirement?

Currently we (creating printed yearbooks for hundreds of customers) use our fork of node-canvas that I haven't touched the code on since December because I know it works and I'd be very nervous about upgrading to the non-forked version with the plethora of font-related bugs I've seen lately.

**Comment by rvagg** [comment]
if it's to become a requirement then we should bump major version to indicate breakage - my use is simple, load a font by pointing to a particular path and then explicitly insert that to the context and refer to it by that name - if pango become necessary then we'd need a migration path for that usage to a pango-happy usage and tbh I don't know what that is (I've messed with fontconfig to no avail)

**Comment by chearon** [comment]
Closed via #715
