### ISSUE TITLE
The published package does not match the code on GitHub

### ISSUE THREAD

**Issue by LinusU** [Automattic/node-canvas#596]
As @jheer pointed out in #588, the file `binding.gyp` that is published to npm is not the same as the one on github. This causes installation issues on both OS X and Linux.

This is the difference:

```diff
diff -u -r github/binding.gyp npm/binding.gyp
--- github/binding.gyp	2015-07-27 10:02:03.000000000 +0200
+++ npm/binding.gyp	2015-07-06 23:08:48.000000000 +0200
@@ -52,12 +52,6 @@
         'src/init.cc',
         'src/PixelArray.cc'
       ],
+      'include_dirs': [
+        '/opt/X11/include',
+      ],
+      'library_dirs': [
+        '/opt/X11/lib',
+      ],
       'conditions': [
         ['OS=="win"', {
           'libraries': [

```

Please upload a clean release as version `1.2.5` (npm doesn't allow patching published material). I would also recommend deprecating version `1.2.4`.

After making sure that the latest `master` is checked out and that **no other changes are present**, the following commands could be run:

```sh
npm deprecate canvas@1.2.4 'broken version'
npm version patch -m 'version: %s'
git push
git push --tags
npm publish
```

@TooTallNate I believe it was you who pushed the last release, would you mind fixing this? :+1:

**Comment by LinusU** [comment]
Ping @kangax, @domenic. Are any of you able to fix this?

**Comment by TooTallNate** [comment]
Can you try 1.2.5?

**Comment by jheer** [comment]
Just tested 1.2.5. Works for me (Mac OS X 10.10.3). Thanks!

**Comment by LinusU** [comment]
It works! (Mac OS X 10.10.4)

**Comment by LinusU** [comment]
@TooTallNate Could you close #598 and #594 as well?

Also, are you looking for more maintainers? I would love to help out, especially since we are using this module at my place of work.

**Comment by kangax** [comment]
@LinusU yes, we're absolutely looking for more help. Thanks for all the support with the latest 1.2.4 issue btw, much appreciated. There's a lot of installation related tickets that ideally should all be sorted out. I expect at least half of them to be irrelevant by now but that might need further examination and/or reproduction. If you can help with that, that would be awesome (since none of the current contributors have much time, afaik, but we're all relying on node-canvas in our projects).

**Comment by LinusU** [comment]
I'll do my best, I was just added to the repo :+1:
