### ISSUE TITLE
Link no longer working on article "node-canvas on Heroku"

### ISSUE THREAD

**Issue by bitflower** [Automattic/node-canvas#723]
The article contains a link to the repository with bundled pre-compiled binaries.

However this link is dead. Do you know if it's available somewhere else?

Is there an alternative way now?

Article:
https://github.com/Automattic/node-canvas/wiki/Installation-on-Heroku

Dead link:
https://github.com/elspoono/node-canvas-heroku

**Comment by diwu1989** [comment]
I'm having trouble running the latest version of node-canvas on heroku as well, we use custom fonts and node canvas seems to crash on that

**Comment by marcsyp** [comment]
Same problem here.  I can't get it to install at all.  An old heroku fork I found is canvas@0.8.2 and requires node-waf and won't build on heroku.  What repo are you using to even get node-canvas to install at all?

Does anyone have a working solution for this?

I will also be using a custom font, so I am really hoping to get this up and running, otherwise I'll be migrating to a windows VM....  which I don't really want to do.

**Comment by zbjornson** [comment]
I just successfully installed canvas 2.0.0-alpha.12 and 1.6.11 on the vanilla heroku-16 stack. Both just worked thanks to prebuilds. If anyone has a need to make a from-source build work, I can look into it.
