### ISSUE TITLE
Feature request: instantiation without `new` keyword

### ISSUE THREAD

**Issue by dbkaplun** [Automattic/node-canvas#831]
Hi all and thanks for making the excellent node-canvas library! It works great and is super fast. My only nitpick is that the `new` keyword is required when instantiating a Canvas/Image. Would be great if I could use Canvas/Image as a plain old JS function which would simplify usage of .apply().

Thanks again for this excellent library!

**Comment by LinusU** [comment]
Personally I would prefer it if we exported a `createCanvas` function instead of the `Canvas` class, since the browser doesn't have a `Canvas` class at all. That way we could ship a `browser.js` shim and be truly isomorphic. As it is now, you cannot write coded that "just works" in both the browser and with node-canvas.

**Comment by LinusU** [comment]
Wrote up some of my thoughts in #833

**Comment by dbkaplun** [comment]
Thanks @LinusU! I agree with most of the ideas in your ticket. I would just like to make clear that this ticket is only regarding the `new` keyword in Canvas/Image instantiation.

**Comment by zbjornson** [comment]
Closing since `new` is required in browsers and specified by ECMA 2015(?).
