### ISSUE TITLE
Text rendering becomes horribly slow after upgrading from 1.6.4 to 1.6.5

### ISSUE THREAD

**Issue by basvanmeurs** [Automattic/node-canvas#920]
Hi all, after upgrading from 1.6.4 to 1.6.5 I started to get the feeling that text rendering had become quite a bit slower. Now I've used the nodejs inspector to investigate the issue and can confirm that there it has become up to 3x as slow for (small) text renderings, caused by the introduction of the parse-css-font module. It has horrible performance, 2x slower than actually rendering the text:

1.6.5:
![node-canvas-1 6 5](https://cloud.githubusercontent.com/assets/120531/25903360/729b2dfa-359c-11e7-8399-3ee6c8d9d380.png)

1.6.4:
![node-canvas-1 6 4](https://cloud.githubusercontent.com/assets/120531/25903355/7197fd16-359c-11e7-99f6-c69c42243f6d.png)

The test script:
```javascript
var Canvas = require('canvas')

var draw = function() {
    var canvas = new Canvas(200, 50);
    var ctx = canvas.getContext('2d');
    ctx.font = "bold 20px Verdana";
    ctx.fillText("text " + Math.random(), 0, 0);
};
setInterval(draw, 10);
```

**Comment by chearon** [comment]
I wasn't really a fan of it tbh, it introduced a number of other dependencies and all we had to do was add `font-style` to the regex. That said, it only looks like a few milliseconds added, are you sure you shouldn't just optimize your calls to `ctx.font`?

**Comment by basvanmeurs** [comment]
Compared to the actual rendering time the difference is huge. I'm using canvas to show a tv guide in which a lot of small texts (programs) are created. As stated, the performance degradation was very noticable. A few milliseconds is very much time if you consider that it's only parsing a very small piece of text... multiply it by 10 and your FPS drops from 60 to 30 which is what I'm facing right now.

How could I optimize the calls to ctx.font? Is there an alternative way of setting the font style, size and face, which causes it not to be parsed?

Besides this, I've had issues with this set of modules before because somewhere in my code I used the global window variable. This module tests for that variable name to decide whether it is in-browser or in nodejs.

**Comment by glebm** [comment]
parse-css-font does the following:

1. First, it splits the string by whitespace into an array of token. Instead of using a regexp, it actually process each character! This is *much* slower in JavaScript than `String#split`. [css-list-helpers/index.js:29](https://github.com/jedmao/css-list-helpers/blob/9fe0be0676b16ffdab2021bfe4b7c9007511cbc8/index.js#L29)
2. Then, it processes each token in a loop. At each iteration, it calls `shift()` on the tokens array. `Array#shift` is `O(n)` in a lot of environments. This is `O(n^2)` in the number of tokens. [parse-css-font/index.js:50](https://github.com/jedmao/parse-css-font/blob/09530328e762ce40a1732d1c3555e2f48975e6ff/index.js#L50)

At this point I stopped investigating `parse-css-font`, as the issues above are enough to make it *very* slow.

I've also looked into the [css-font-parser](https://github.com/bramstein/css-font-parser) package. This package has no dependencies, and is likely faster as it avoids some of the pitfalls of `parse-css-font`. However, it also parses the declaration character by character (instead of splitting it directly into tokens using `String#split`).

Perhaps going back to the regexp is the most sensible choice here, short of writing a new font declaration parser.

If you decide to use a package for this anyway, please consider replacing `parse-css-font` with `css-font-parser`, as it is likely much faster.

**Comment by LinusU** [comment]
Another thing that we should probably do regardless would be to cache the font parsing
