### ISSUE TITLE
SVG images with small dimensions render with bad quality

### ISSUE THREAD

**Issue by saschagehlich** [Automattic/node-canvas#957]
## Issue or Feature
Rendering an SVG file that has small dimensions (in my example 62x58 pixels) should be re-rasterized when changing the image's dimension properties (as it works in browsers).

## Steps to Reproduce
In this example I'm loading a small SVG image and multiply its dimensions by 10 in order to render it with higher quality onto the canvas. After changing the dimensions, getting them returns the same values. Rendering it to the canvas causes a very blurry image.

```js
import path from 'path'
import fs from 'fs'
import { createCanvas, loadImage } from 'canvas'

const canvas = createCanvas(500, 500)
loadImage(path.resolve(__dirname, 'some-small-image.svg'))
  .then(image => {
    console.log(image.width, 'x', image.height) // 62 x 58

    image.width = image.width * 10
    image.height = image.height * 10

    console.log(image.width, 'x', image.height) // 62 x 58

    const context = canvas.getContext('2d')
    context.drawImage(image, 0, 0, 500, 500)

    const buf = canvas.toBuffer()
    fs.writeFileSync('test.png', buf)
  })
```

The resulting image looks like this:

![test](https://user-images.githubusercontent.com/119684/29163737-a44ba85c-7dbd-11e7-9227-c3970d288acf.png)

## Your Environment
* Version of node-canvas (e.g. 1.4.0): Current master
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): node v8.1.2, OSX 10.12.5 Sierra

**Comment by zbjornson** [comment]
Definitely. This [came up in the PR](https://github.com/Automattic/node-canvas/pull/811#issuecomment-257170140); right now when you load an SVG to an image it's immediately rasterized.

**Comment by LinusU** [comment]
Would love a PR for this ❤️

**Comment by asturur** [comment]
The plain html5 api behaves exactly like that.
If you pick up an svg that is defined as 62 x 58 px you will get exactly that numbers of pixels whatever you do with the image dimensions.

I believe this would be an improvement of course, but i also believe this should be an option to set on or off, since that would diverge from standard canvas, making getting the same results betweens browsers and node more difficult.

**Comment by saschagehlich** [comment]
@asturur https://jsfiddle.net/5sdg666d/1/

**Comment by saschagehlich** [comment]
BTW, PR here: #964

**Comment by asturur** [comment]
Good.
This is completely new for me.
I swear i had to always to change the widht of the image in the markup to get something better.

**Comment by kayahr** [comment]
Not sure if I understand this problem (and the fix if there was one?) correctly. The comments say that node-canvas behaves like browsers do and re-rasterizes the image when changing the width/height properties? 

Well that's not what I'm experiencing here. In Chrome and Firefox it doesn't matter at all to which these properties are set, the SVG is rasterized on draw and not when setting these parameters. So the output is always smooth as you expect from a vector format. 

But when rendering an SVG with small width/height properties (defined in the doucment or set manually with width/height attributes on image object) with node-canvas then the output is very pixelated. So currently for node-canvas I have to scale the width/height properties manually to get a good quality output while this is totally unnecessary in browsers.

Is this the expected behavior? Or is this a new bug or related to this one?

**Comment by LinusU** [comment]
@kayahr it seems like this issue (and the PR that fixed it) addressed changing `.width` and `.height` of the image object.

Could you open a new issue for re-rasterizing the image when a small image is drawn large e.g. with `context.drawImage(image, 0, 0, image.width * 10, image.height * 10)`

**Comment by kayahr** [comment]
@LinusU New issue is created: https://github.com/Automattic/node-canvas/issues/1555

**Comment by asturur** [comment]
That issue alreadu exist and is #1474 
We should link the issue together and keep one open for clarity.

**Comment by LinusU** [comment]
We should link them together, but I think that they might cover something slightly different?

As far as I understand it, #1474 covers when the context is currently scaled, with `ctx.scale(20, 20)`. Whereas #1555 covers when drawing an image larger than it's size, with `ctx.drawImage(img, x, y, largeWidth, largeHeight)`.

I suspect that one could be fixed without necessarily fixing the other (although a general solution would of course be preferred) so I think that there might be value in keeping them both open ☺️

**Comment by asturur** [comment]
I think what happen internally is exactly the same. Is detecting the destination scale and act accordingly.
For example if you use the 9 args version, you could still have a drawImage that is using as destination the exact source width and exact source height, but it could have a smaller source width and source height and so need a scale anyway.

I tried to work on it, and i gave up quickly, but i would love that if someone would sit down and try solve it would keep in mind the problem fully and not writing a fix for half of it.

**Comment by asturur** [comment]
So to be clear the situation to fix are:
- drawImage(svg, 0, 0, largeWidth, largeHeight)
- drawImage(svg, Sx, Sy, Sw, Sh, x, y, anyWidth, anyHeight) where anyWidth is different from Sw and same fore height
- any of the above on a scaled context

The fix also, would probably make not relevant anymore the current fix, the one that resize when width/height changes.
