### ISSUE TITLE
Module canvas was not found

### ISSUE THREAD

**Issue by YanBeat** [Automattic/node-canvas#999]
## Issue or Feature

When running node -> C:\Users\Default\Desktop\AwesomeCanvas

```
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module not found.
\\?\C:\Users\Default\Desktop\AwesomeCanvas\node_modules\canvas\build\Release\canvas.node
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Default\Desktop\AwesomeCanvas\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

Browsing to module path in the error, folder and file do exist.
_Does work when compiling with node64 & GTK64_

## Steps to Reproduce
npm i canvas@v2.0.0-alpha.5 (same error with other versions I've tested)
node32bit -> C:\Users\Default\Desktop\AwesomeCanvas

## Your Environment
* Version of node-canvas: v2.0.0-alpha.5
* Environment: v.6.11.3 x86
* gtk+-bundle_2.24.10-20120208_win32
* libjpeg-turbo-1.5.1-vc.exe
* Windows 10 Pro x64

**Comment by zbjornson** [comment]
This suggests that there's a 32-bit/64-bit mismatch *somewhere*, although it looks like you've been careful about this. Do you have libjpeg-turbo installed (or librsvg), and if so, is that also 32-bit?

**Comment by YanBeat** [comment]
Though it was optional but after installing libjpeg-turbo-1.5.1-vc.exe, ran `> npm i` after deleting canvas module, still the same problem.

**Comment by zbjornson** [comment]
Sorry, it is optional -- I just wanted to be sure that if you *were* building with libjpeg-turbo, that it was also 32-bits.

I don't have a lot more to suggest unfortunately. If you haven't already, I would try `node-gyp rebuild` (or deleting your node_modules/canvas directory and re-installing node-canvas) so that you're definitely picking up the 32-bit build and definitely don't have the 64-bit files hanging around. (The build process copies the dependencies to `canvas/build/Release/`, so you might have both the 64-bit and 32-bit dependencies there?)

**Comment by YanBeat** [comment]
Here are the list of files: 
```
jpeg62
libcairo-2
libexpat-1
libfontconfig-1
libglib-2.0-0
libgmodule-2.0-0
libgobject-2.0-0
libgthread-2.0-0
libpango-1.0-0
libpangocairo-1.0-0
libpangoft2-1.0-0
libpangowin32-1.0-0
libpng14-14
zlib1
```

I can also see when running `node-gyp rebuild` missing files: 
```
C:\GTK\bin\libfreetype-6.dll
C:\GTK\bin\libintl-8.dll
```

However I did install it from the link provided in wiki.
